#DUBBOX
dubbox:
  application: 
    name: hhhhhh-item
    organization: dubbox
    owner: Jaward
  annotation:
    package: com.hhhhhh.item.servant

spring:
  profiles:
    active: @profiles.active@

mybatis:
  type-aliases-package: com.hhhhhh.pojo
  mapper-locations: classpath:com/hhhhhh/mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Redis
redisKey:
  # 缓存时间 默认半小时
  expire_time: 1800
  prefix:
    item_info_profix: 'ITEM_INFO:'
  suffix:
    item_info_base_suffix: ':BASE'
    item_info_desc_suffix: ':DESC'
